Returning false in 'start' doesn't cause TypeError
TypeError: $.ajax($.extend({
	beforeSend: function (xhr) {
		return inner.fire({
			name: "start",
			off: settings.off || {}
		}, xhr);
	}
}, settings)).done is not a function...

fix